from __future__ import annotations

import copy
import json
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Annotated, Dict, List, Tuple

from openlifu.db.session import SolutionInfo
from openlifu.geo.point import Point
from openlifu.geo.transforms import ArrayTransform
from openlifu.util.annotations import OpenLIFUFieldData
from openlifu.util.json import PYFUSEncoder
from openlifu.util.strings import sanitize


@dataclass
class PlanningSession:
    """A working document for developing a treatment :class:`Plan`.

    Owns targets, virtual-fit results, and pre-solutions. Mutable throughout its
    lifetime; only explicit :meth:`to_file` or a database ``write_planning_session``
    call touches disk.

    "Finalizing" a PlanningSession produces an immutable :class:`Plan` (a
    ``db.finalize_plan(...)`` helper, added in a later commit). The same
    PlanningSession may finalize multiple Plans over time; every Plan id it has
    produced is tracked in :attr:`finalized_plan_ids`.

    ``pre_solutions`` entries are :class:`SolutionInfo` references to Solutions
    stored at subject scope (``subjects/{sid}/solutions/``). The same Solution
    file may be referenced by this session's ``pre_solutions`` list and one or
    more Plans finalized from it, without duplication on disk.
    """

    id: Annotated[str | None, OpenLIFUFieldData("Planning session ID", "ID of this planning session")] = None
    """ID of this planning session"""

    name: Annotated[str | None, OpenLIFUFieldData("Planning session name", "Planning session name")] = None
    """Planning session name"""

    subject_id: Annotated[str | None, OpenLIFUFieldData("Subject ID", "ID of the parent subject of this planning session")] = None
    """ID of the parent subject of this planning session"""

    volume_id: Annotated[str | None, OpenLIFUFieldData("Volume ID", "ID of the subject volume associated with this planning session")] = None
    """ID of the subject volume associated with this planning session"""

    protocol_id: Annotated[str | None, OpenLIFUFieldData("Protocol ID", "ID of the protocol used for this planning session")] = None
    """ID of the protocol used for this planning session"""

    transducer_id: Annotated[str | None, OpenLIFUFieldData("Transducer ID", "ID of the transducer associated with this planning session")] = None
    """ID of the transducer associated with this planning session"""

    date_created: Annotated[datetime, OpenLIFUFieldData("Date created", "Date of creation of the planning session")] = field(default_factory=datetime.now)
    """Date of creation of the planning session"""

    date_modified: Annotated[datetime, OpenLIFUFieldData("Date modified", "Date of last modification of the planning session")] = field(default_factory=datetime.now)
    """Date of last modification of the planning session"""

    targets: Annotated[List[Point], OpenLIFUFieldData("Targets", "Targets saved to this planning session")] = field(default_factory=list)
    """Targets saved to this planning session"""

    virtual_fit_results: Annotated[Dict[str, List[Tuple[bool, ArrayTransform]]], OpenLIFUFieldData("Virtual fit results", "Dictionary mapping target IDs to a list of (approval, transform) pairs, one entry per virtual-fit candidate for that target.")] = field(default_factory=dict)
    """Virtual fit results.

    Dictionary mapping target IDs to a list of ``(approval, transform)`` pairs, where
    ``approval`` is a boolean indicating whether the specific virtual fit ``transform``
    has been approved for sonication, and ``transform`` is a transducer array-to-volume
    transform generated by the virtual fit for that target.
    """

    pre_solutions: Annotated[List[SolutionInfo], OpenLIFUFieldData("Pre-solutions", "SolutionInfo references to pre-solutions computed against virtual-fit poses on this planning session. Actual Solution files live at subject scope.")] = field(default_factory=list)
    """:class:`SolutionInfo` references to pre-solutions computed against virtual-fit
    poses on this planning session.

    The actual :class:`~openlifu.plan.Solution` files live at subject scope
    (``subjects/{sid}/solutions/``). Solutions on disk under the subject that have no
    matching ``SolutionInfo`` here (and are not referenced from any Plan or
    SonicationSession) are candidates for orphan cleanup, but that cleanup is not
    performed automatically by session save.
    """

    finalized_plan_ids: Annotated[List[str], OpenLIFUFieldData("Finalized plan IDs", "IDs of every Plan this planning session has finalized. Each Plan is immutable; multiple Plans per session are supported.")] = field(default_factory=list)
    """IDs of every :class:`Plan` this planning session has finalized. Each Plan is
    immutable; multiple Plans per session are supported."""

    attrs: Annotated[dict, OpenLIFUFieldData("Custom attributes", "Dictionary of additional custom attributes to save to the planning session")] = field(default_factory=dict)
    """Dictionary of additional custom attributes to save to the planning session"""

    def __post_init__(self):
        if self.id is None and self.name is None:
            self.id = "planning_session"
        if self.id is None:
            self.id = sanitize(self.name, "snake")
        if self.name is None:
            self.name = self.id
        if isinstance(self.targets, Point):
            self.targets = [self.targets]
        else:
            self.targets = list(self.targets)

    @staticmethod
    def from_file(filename) -> PlanningSession:
        """Load a PlanningSession from a JSON file."""
        with open(filename) as f:
            return PlanningSession.from_dict(json.load(f))

    @staticmethod
    def from_dict(d: Dict) -> PlanningSession:
        """Reconstruct a PlanningSession from its dictionary representation."""
        d = dict(d)  # shallow copy; we mutate below
        if "date_created" in d and isinstance(d["date_created"], str):
            d["date_created"] = datetime.fromisoformat(d["date_created"])
        if "date_modified" in d and isinstance(d["date_modified"], str):
            d["date_modified"] = datetime.fromisoformat(d["date_modified"])
        if "targets" in d:
            targets = d["targets"]
            if isinstance(targets, list):
                d["targets"] = [
                    p if isinstance(p, Point) else Point.from_dict(p) for p in targets
                ]
            elif isinstance(targets, dict):
                d["targets"] = [Point.from_dict(targets)]
            elif isinstance(targets, Point):
                d["targets"] = [targets]
        if "virtual_fit_results" in d:
            d["virtual_fit_results"] = {
                target_id: [
                    (approval, t if isinstance(t, ArrayTransform) else ArrayTransform.from_dict(t))
                    for approval, t in list_of_transforms
                ]
                for target_id, list_of_transforms in d["virtual_fit_results"].items()
            }
        if "pre_solutions" in d:
            d["pre_solutions"] = [
                s if isinstance(s, SolutionInfo) else SolutionInfo(**s)
                for s in d["pre_solutions"]
            ]
        return PlanningSession(**d)

    def to_dict(self) -> Dict:
        """Serialize the PlanningSession to a dictionary."""
        d = copy.deepcopy(self.__dict__)
        d["date_created"] = d["date_created"].isoformat()
        d["date_modified"] = d["date_modified"].isoformat()
        d["targets"] = [p.to_dict() for p in d["targets"]]
        d["virtual_fit_results"] = {
            target_id: [(approval, asdict(t)) for [approval, t] in list_of_transforms]
            for target_id, list_of_transforms in d["virtual_fit_results"].items()
        }
        d["pre_solutions"] = [asdict(s) for s in d["pre_solutions"]]
        return d

    @staticmethod
    def from_json(json_string: str) -> PlanningSession:
        """Load a PlanningSession from a JSON string."""
        return PlanningSession.from_dict(json.loads(json_string))

    def to_json(self, compact: bool) -> str:
        """Serialize a PlanningSession to a JSON string."""
        if compact:
            return json.dumps(self.to_dict(), separators=(",", ":"), cls=PYFUSEncoder)
        return json.dumps(self.to_dict(), indent=4, cls=PYFUSEncoder)

    def to_file(self, filename) -> None:
        """Write the PlanningSession to a JSON file, creating parent directories as needed."""
        Path(filename).parent.parent.mkdir(exist_ok=True)  # planning_sessions directory
        Path(filename).parent.mkdir(exist_ok=True)         # {planning_session_id} directory
        with open(filename, "w") as f:
            f.write(self.to_json(compact=False))

    def update_modified_time(self, time: datetime | None = None) -> None:
        if time is None:
            time = datetime.now()
        self.date_modified = time
